version: '3'
services:
  # MySQL Database
  mysqldb:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - 3306:3306
    volumes:
      - dockerAngularSpringDatabaseData:/var/lib/mysql
    networks:
      - back

  # Spring Boot Backend
  spring-backend:
    build:
      context: ./
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    networks:
      - back
volumes:
  dockerAngularSpringDatabaseData:

networks:
  back: